apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Chart.Name }}-ingress
  namespace: {{ .Values.namespace | quote }}
  annotations:
    kubernetes.io/ingress.class: "gce"
spec:
  rules:
    - host: {{ index .Values.ingress.hosts 0 "host" | quote }}
      http:
        paths:
          - path: {{ index .Values.ingress.hosts 0 "paths" 0 | quote }}
            pathType: Prefix
            backend:
              service:
                name: {{ .Chart.Name }}-service
                port:
                  number: {{ .Values.service.port }}