apiVersion: v1
kind: ResourceQuota
metadata:
  name: {{ .Chart.Name }}-resource-quota
  namespace: {{ .Values.namespace }}
spec:
  hard:
    requests.cpu: "0.5"
    requests.memory: "512Mi"
    limits.cpu: "1"
    limits.memory: "1Gi"