replicaCount: 2

namespace: meu-namespace

image:
  repository: msassaki/hello-world
  tag: latest

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  hosts:
    - host: hello-world.example.com
      paths:
        - "/"